name: WebGoat CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up JDK 21
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      # 3. Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # 4. Verify Java version
      - name: Check Java version
        run: java -version

      # 5. Build and run tests in headless mode
      - name: Build and test WebGoat
        env:
          MAVEN_OPTS: "-Djava.awt.headless=true"
        # run: mvn clean verify -B 
        run: mvn --no-transfer-progress verify

